# Generated by Django 3.2.5 on 2021-08-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('title', models.CharField(default='Comment', max_length=50)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('category_description', models.TextField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_App.categorygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='default3.jpg', upload_to='')),
                ('is_vege', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='Shop_App.ProductCategory')),
            ],
        ),
    ]
