# Generated by Django 3.2.5 on 2021-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
