# Generated by Django 3.2.5 on 2021-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_App', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default3.jpg', upload_to=''),
        ),
    ]
